### ISSUE TITLE
ParseError: More data is available after end-of-object.

### ISSUE THREAD

**Issue by sophieyoung717** [danielgindi/node-bson-json-transform#2]
I tried this: 

var fs = require('fs');
var BsonJsonTransform = require('bson-json-transform');

fs
    .createReadStream('users.bson')
    .pipe(BsonJsonTransform({ preserveInt64: 'string' }))
    .pipe(fs.createWriteStream('users.json'))
    .on('end', function (data) {
        console.log('No more data!');
    });

The error is:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ParseError: More data is available after end-of-object.
    at BsonJsonTransform._transform (/Users/yingyang/Documents/JavaScript/node_modules/bson-json-transform/index.js:674:28)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Writable.write (_stream_writable.js:220:11)
    at ReadStream.ondata (_stream_readable.js:561:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)

**Comment by danielgindi** [comment]
Could you provide a sample of the BSON that you are using?

**Comment by danielgindi** [comment]
Basically this means that your BSON may contain more data after the end of the object was detected. Maybe it's an array of BSONs (Which is not a standard of the BSON, but many do that - so the library supports it)

Try to add `arrayOfBsons: true` to the options that you pass
